import { v2 as cloudinary } from 'cloudinary';
import { env } from '../lib/env.js';
import { logger } from '../lib/logger.js';
import { AppError } from '../lib/errors.js';
import { isServiceAvailable } from '../lib/serviceAvailability.js';

// Initialize Cloudinary SDK
cloudinary.config({
  cloud_name: env.CLOUDINARY_CLOUD_NAME,
  api_key: env.CLOUDINARY_API_KEY,
  api_secret: env.CLOUDINARY_API_SECRET,
  secure: true,
});

export interface UploadResult {
  secure_url: string;
  public_id: string;
  format: string;
}

/**
 * Upload an identity or KYC document to Cloudinary with `type: 'authenticated'`.
 * Authenticated assets are completely private and cannot be downloaded or viewed
 * via public URLs without an expiring cryptographic signature generated by the backend.
 */
export async function uploadKycDocument(
  tenantId: string,
  docType: string,
  file: File,
  isPrivate: boolean = true,
): Promise<UploadResult> {
  if (!isServiceAvailable('cloudinary')) {
    throw new AppError(
      'Cloudinary storage is not configured on this server.',
      503,
      'STORAGE_UNAVAILABLE',
      undefined,
      'Document storage is temporarily unavailable. Please contact the property administrator.',
    );
  }

  const arrayBuffer = await file.arrayBuffer();
  const buffer = Buffer.from(arrayBuffer);
  const base64Data = `data:${file.type};base64,${buffer.toString('base64')}`;

  const isPdf = file.type === 'application/pdf';
  const resourceType = isPdf ? 'raw' : 'image';

  try {
    const result = await cloudinary.uploader.upload(base64Data, {
      folder: `tenet_pg/tenants/${tenantId}/kyc`,
      public_id: `${docType}_${Date.now()}`,
      resource_type: resourceType,
      type: isPrivate ? 'authenticated' : 'upload',
    });

    return {
      secure_url: result.secure_url,
      public_id: result.public_id,
      format: result.format || (isPdf ? 'pdf' : 'jpg'),
    };
  } catch (err) {
    logger.error({ err, tenantId, docType }, 'Cloudinary authenticated document upload failed');
    throw new AppError(
      `Document upload failed: ${err instanceof Error ? err.message : 'Storage error'}`,
      502,
      'UPLOAD_FAILED',
      undefined,
      'Failed to upload the identity document. Please try again.',
    );
  }
}

/**
 * Generate a cryptographically signed, short-lived delivery URL (default 10 mins)
 * to view or download a private authenticated identity document.
 */
export function generatePrivateDocumentUrl(
  publicId: string,
  format: string = 'jpg',
  expiresInSeconds: number = 600,
): string {
  if (!isServiceAvailable('cloudinary') || !publicId) {
    return '';
  }

  const expiresAt = Math.floor(Date.now() / 1000) + expiresInSeconds;
  const isRaw = format.toLowerCase() === 'pdf';

  try {
    if (isRaw) {
      return cloudinary.utils.private_download_url(publicId, format, {
        resource_type: 'raw',
        type: 'authenticated',
        expires_at: expiresAt,
        attachment: false,
      });
    }

    return cloudinary.url(publicId, {
      type: 'authenticated',
      sign_url: true,
      secure: true,
      expires_at: expiresAt,
    });
  } catch (err) {
    logger.error({ err, publicId }, 'Failed to generate signed document URL');
    return '';
  }
}

/**
 * Permanently delete an authenticated asset from Cloudinary storage upon document replacement
 * or tenant deletion to prevent orphaned data leaks.
 */
export async function deleteKycDocument(
  publicId?: string,
  isRaw: boolean = false,
  isPrivate: boolean = true,
): Promise<void> {
  if (!isServiceAvailable('cloudinary') || !publicId) return;

  try {
    await cloudinary.uploader.destroy(publicId, {
      type: isPrivate ? 'authenticated' : 'upload',
      resource_type: isRaw ? 'raw' : 'image',
    });
    logger.info({ publicId }, 'Cloudinary KYC document deleted successfully');
  } catch (err) {
    logger.warn({ err, publicId }, 'Failed to delete Cloudinary KYC document');
  }
}
